apiVersion: apps/v1
kind: Deployment
metadata:
  name: snappy-backend
spec:
  selector:
    matchLabels:
      app: snappy-backend
  template:
    metadata:
      labels:
        app: snappy-backend
    spec:
      containers:
      - name: snappy-backend
        image: dabhidhruvraj/snappy-backend:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: MONGO_URL
            value: "mongodb://mongodb-service.default.svc.cluster.local:27017/chat"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: chat
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: password
